/**
 * Incbin — the core binary-to-TypeScript embedding engine.
 *
 * This implements the "incbin" philosophy for TypeScript:
 *  1. Read a binary file (ONNX model, tokenizer JSON, etc.)
 *  2. Optionally compress (gzip) to reduce size
 *  3. Encode as base64
 *  4. Compute SHA256 integrity hash
 *  5. Generate a TypeScript module that exports the data as constants
 *
 * The generated module can be imported at runtime — the binary data IS code.
 * No file system access needed, no network requests, just import and decode.
 *
 * Usage (via CLI):
 *   tsx scripts/incbin.ts --input model_int8.onnx --output src/weights/model.inc.ts --name MODEL
 *
 * Usage (via API):
 *   incbin({ inputPath: 'model.onnx', outputPath: 'src/weights/model.inc.ts', exportName: 'MODEL' })
 */

import * as fs from 'fs';
import * as path from 'path';
import * as crypto from 'crypto';
import { gzipSync, brotliCompressSync } from 'zlib';

// ─── Types ─────────────────────────────────────────────────

export interface IncbinOptions {
  /** Path to the input binary file */
  inputPath: string;
  /** Output TypeScript file path */
  outputPath: string;
  /** Name prefix for the exported constants (e.g., 'MODEL' → MODEL_BASE64, MODEL_SHA256) */
  exportName: string;
  /** Maximum size per chunk in bytes (default: 50 * 1024 * 1024 = 50MB) */
  chunkSize?: number;
  /** Compression mode: 'none' | 'gzip' | 'brotli' */
  compress?: 'none' | 'gzip' | 'brotli';
  /** Whether to split large files into chunks */
  splitChunks?: boolean;
  /** Whether to generate chunk manifest */
  generateManifest?: boolean;
}

export interface IncbinResult {
  outputFiles: string[];
  totalSize: number;
  compressedSize: number;
  sha256: string;
  chunkCount: number;
}

// ─── Constants ─────────────────────────────────────────────

const DEFAULT_CHUNK_SIZE = 50 * 1024 * 1024; // 50MB
const CHUNK_THRESHOLD = 200 * 1024 * 1024; // 200MB — above this, split into chunks

// ─── Main Entry Point ──────────────────────────────────────

export async function incbin(options: IncbinOptions): Promise<IncbinResult> {
  const {
    inputPath,
    outputPath,
    exportName,
    chunkSize = DEFAULT_CHUNK_SIZE,
    compress = 'gzip',
    splitChunks = true,
    generateManifest = true,
  } = options;

  // Read input
  const rawBuffer = fs.readFileSync(inputPath);
  const rawSize = rawBuffer.length;

  // Compress if requested
  let compressedBuffer: Buffer;
  let compressionUsed: string;
  if (compress === 'gzip') {
    compressionUsed = 'gzip';
    compressedBuffer = gzipSync(rawBuffer, { level: 9 });
  } else if (compress === 'brotli') {
    compressionUsed = 'brotli';
    compressedBuffer = brotliCompressSync(rawBuffer, {
      params: { [require('zlib').constants.BROTLI_PARAM_QUALITY]: 11 },
    });
  } else {
    compressionUsed = 'none';
    compressedBuffer = rawBuffer;
  }

  const compressedSize = compressedBuffer.length;

  // Base64 encode
  const base64 = compressedBuffer.toString('base64');

  // Compute SHA256 of the ORIGINAL (uncompressed) data
  const sha256 = crypto.createHash('sha256').update(rawBuffer).digest('hex');

  // Ensure output directory exists
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });

  const outputFiles: string[] = [];

  // Decide: single file or chunked?
  if (splitChunks && base64.length > CHUNK_THRESHOLD) {
    // Split into chunks
    const chunks = splitBase64(base64, chunkSize);
    const manifest = generateChunkManifest(chunks, rawSize, sha256, chunkSize);

    // Write chunk manifest
    const manifestPath = outputPath.replace(/\.inc\.ts$/, '.chunk.manifest.ts');
    writeChunkManifest(manifestPath, manifest);
    outputFiles.push(manifestPath);

    // Write each chunk
    for (let i = 0; i < chunks.length; i++) {
      const chunkPath = outputPath.replace(
        /\.inc\.ts$/,
        `.chunk_${String(i).padStart(4, '0')}.inc.ts`,
      );
      const chunkHash = crypto
        .createHash('sha256')
        .update(Buffer.from(chunks[i]!, 'base64'))
        .digest('hex');

      writeChunkFile(chunkPath, exportName, i, chunks[i]!, chunkHash);
      outputFiles.push(chunkPath);
    }

    return {
      outputFiles,
      totalSize: rawSize,
      compressedSize,
      sha256,
      chunkCount: chunks.length,
    };
  }

  // Single file
  const filePath = outputPath.endsWith('.ts') ? outputPath : `${outputPath}.ts`;
  writeSingleFile(filePath, exportName, base64, sha256, rawSize, compressionUsed);
  outputFiles.push(filePath);

  return {
    outputFiles,
    totalSize: rawSize,
    compressedSize,
    sha256,
    chunkCount: 1,
  };
}

// ─── File Writers ──────────────────────────────────────────

function writeSingleFile(
  filePath: string,
  name: string,
  base64: string,
  sha256: string,
  rawSize: number,
  compression: string,
): void {
  const upper = name.toUpperCase();

  const content = `/**
 * @generated — DO NOT EDIT
 * Generated by incbin at ${new Date().toISOString()}
 *
 * Embedded binary: ${path.basename(filePath)}
 * Original size: ${formatBytes(rawSize)}
 * Compression: ${compression}
 */

/** Base64-encoded model weights */
export const ${upper}_BASE64 = ${JSON.stringify(base64)};

/** SHA256 hash of the original (uncompressed) data */
export const ${upper}_SHA256 = '${sha256}';

/** Original uncompressed size in bytes */
export const ${upper}_SIZE = ${rawSize};

/** Compression method used */
export const ${upper}_COMPRESSION = '${compression}';
`;

  fs.writeFileSync(filePath, content, 'utf-8');
  console.log(`  ✓ incbin: ${filePath} (${formatBytes(Buffer.byteLength(content, 'utf-8'))})`);
}

function writeChunkFile(
  filePath: string,
  name: string,
  index: number,
  chunkBase64: string,
  chunkHash: string,
): void {
  const upper = name.toUpperCase();

  const content = `/**
 * @generated — DO NOT EDIT
 * Chunk ${index} of ${name}
 * Generated by incbin at ${new Date().toISOString()}
 */

/** Base64-encoded weight chunk */
export const CHUNK_BASE64 = ${JSON.stringify(chunkBase64)};

/** SHA256 hash of this chunk */
export const CHUNK_SHA256 = '${chunkHash}';

/** Chunk index */
export const CHUNK_INDEX = ${index};
`;

  fs.writeFileSync(filePath, content, 'utf-8');
  console.log(`  ✓ incbin chunk ${index}: ${filePath}`);
}

function writeChunkManifest(
  manifestPath: string,
  manifest: ChunkManifestData,
): void {
  const content = `/**
 * @generated — DO NOT EDIT
 * Chunk manifest — generated by incbin at ${new Date().toISOString()}
 */

export const CHUNK_MANIFEST = ${JSON.stringify(manifest, null, 2)};
`;

  fs.writeFileSync(manifestPath, content, 'utf-8');
  console.log(`  ✓ incbin manifest: ${manifestPath}`);
}

// ─── Helpers ───────────────────────────────────────────────

interface ChunkManifestData {
  totalSize: number;
  sha256: string;
  chunkSize: number;
  chunkCount: number;
  chunks: Array<{
    index: number;
    offset: number;
    size: number;
    sha256: string;
  }>;
}

function splitBase64(base64: string, chunkSize: number): string[] {
  // chunkSize is in bytes of original data, base64 is ~1.33x larger
  const base64ChunkSize = Math.ceil(chunkSize * 1.34);
  const chunks: string[] = [];

  for (let i = 0; i < base64.length; i += base64ChunkSize) {
    chunks.push(base64.slice(i, i + base64ChunkSize));
  }

  return chunks;
}

function generateChunkManifest(
  chunks: string[],
  totalSize: number,
  sha256: string,
  chunkSize: number,
): ChunkManifestData {
  let offset = 0;
  const chunkList = chunks.map((chunk, index) => {
    const chunkData = Buffer.from(chunk, 'base64');
    const chunkHash = crypto
      .createHash('sha256')
      .update(chunkData)
      .digest('hex');
    const size = chunkData.length;
    const entry = { index, offset, size, sha256: chunkHash };
    offset += size;
    return entry;
  });

  return {
    totalSize,
    sha256,
    chunkSize,
    chunkCount: chunks.length,
    chunks: chunkList,
  };
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  if (bytes < 1024 * 1024 * 1024)
    return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
  return `${(bytes / (1024 * 1024 * 1024)).toFixed(2)} GB`;
}

// ─── CLI Entry Point ───────────────────────────────────────

// Run as CLI when executed directly
if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((err) => {
    console.error('❌ incbin failed:', err.message);
    process.exit(1);
  });
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);

  // Parse CLI args
  const inputIdx = args.indexOf('--input');
  const outputIdx = args.indexOf('--output');
  const nameIdx = args.indexOf('--name');
  const compressIdx = args.indexOf('--compress');
  const chunkSizeIdx = args.indexOf('--chunk-size');
  const noSplitIdx = args.indexOf('--no-split');

  if (inputIdx === -1 || outputIdx === -1 || nameIdx === -1) {
    console.error(`
Usage: tsx scripts/incbin.ts --input <file> --output <file> --name <exportName> [options]

Options:
  --input <path>       Input binary file
  --output <path>      Output TypeScript file (.inc.ts)
  --name <name>        Export constant name prefix
  --compress <mode>    Compression: none | gzip | brotli (default: gzip)
  --chunk-size <mb>    Chunk size in MB (default: 50)
  --no-split           Disable chunk splitting

Example:
  tsx scripts/incbin.ts --input model_int8.onnx --output src/weights/model.inc.ts --name MODEL
`);
    process.exit(1);
  }

  const inputPath = args[inputIdx + 1]!;
  const outputPath = args[outputIdx + 1]!;
  const exportName = args[nameIdx + 1]!;
  const compress =
    compressIdx !== -1
      ? (args[compressIdx + 1] as 'none' | 'gzip' | 'brotli')
      : 'gzip';
  const chunkSizeMB = chunkSizeIdx !== -1 ? parseInt(args[chunkSizeIdx + 1]!) : 50;
  const splitChunks = noSplitIdx === -1;

  console.log(`\n📦 incbin: embedding "${path.basename(inputPath)}" → "${outputPath}"`);
  console.log(`  Compression: ${compress}`);
  console.log(`  Chunking: ${splitChunks ? `enabled (${chunkSizeMB}MB)` : 'disabled'}`);

  const result = await incbin({
    inputPath,
    outputPath,
    exportName,
    chunkSize: chunkSizeMB * 1024 * 1024,
    compress,
    splitChunks,
  });

  console.log(`\n✅ incbin complete:`);
  console.log(`  Output files: ${result.outputFiles.length}`);
  console.log(`  Raw size: ${formatBytes(result.totalSize)}`);
  console.log(`  Compressed: ${formatBytes(result.compressedSize)}`);
  console.log(`  Ratio: ${((result.compressedSize / result.totalSize) * 100).toFixed(1)}%`);
  console.log(`  SHA256: ${result.sha256.substring(0, 16)}...`);
  console.log(`  Chunks: ${result.chunkCount}`);
}
