#!/usr/bin/env node
/**
 * Prepare GitHub Pages deployment.
 *
 * Generates/updates docs/index.html with links to API docs, coverage, and benchmarks.
 * Called by the CI deploy-pages job.
 */

const fs = require('fs');
const path = require('path');

const DOCS_DIR = path.resolve(__dirname, '..', 'docs');
const PKG_JSON = require(path.resolve(__dirname, '..', 'package.json'));

// Read benchmark data if available
let benchmarkData = null;
try {
  benchmarkData = JSON.parse(
    fs.readFileSync(path.join(DOCS_DIR, 'benchmark', 'benchmark-report.json'), 'utf-8'),
  );
} catch {
  // No benchmark data
}

// Read coverage data
let coveragePct = null;
try {
  const cov = JSON.parse(
    fs.readFileSync(path.join(DOCS_DIR, 'coverage', 'coverage-summary.json'), 'utf-8'),
  );
  if (cov?.total?.lines) {
    coveragePct = Math.round(cov.total.lines.pct);
  }
} catch {
  // No coverage data
}

// Build benchmark table rows
function benchmarkTable() {
  if (!benchmarkData?.configs?.length) {
    return '<tr><td colspan="4">No benchmark data available</td></tr>';
  }
  return benchmarkData.configs
    .map(
      (c) =>
        `<tr>
      <td>${c.config}</td>
      <td>${c.batchSize}</td>
      <td>${c.avgLatencyMs} ms</td>
      <td>${c.throughputTokensPerSec} tok/s</td>
    </tr>`,
    )
    .join('\n');
}

const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>embed-code-ts — nomic-embed-code int8 for Node.js</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #1a1a2e; max-width: 960px; margin: 0 auto; padding: 2rem; }
    h1 { font-size: 2rem; margin-bottom: 0.5rem; }
    h2 { font-size: 1.4rem; margin-top: 2rem; margin-bottom: 0.5rem; border-bottom: 2px solid #e0e0e0; padding-bottom: 0.25rem; }
    .subtitle { color: #666; margin-bottom: 1.5rem; }
    table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
    th, td { padding: 0.5rem 0.75rem; text-align: left; border-bottom: 1px solid #e0e0e0; }
    th { background: #f5f5f5; font-weight: 600; }
    .badge { display: inline-block; padding: 0.2rem 0.6rem; border-radius: 4px; font-size: 0.85rem; font-weight: 600; }
    .badge-green { background: #d4edda; color: #155724; }
    .badge-yellow { background: #fff3cd; color: #856404; }
    a { color: #2563eb; text-decoration: none; }
    a:hover { text-decoration: underline; }
    .nav { display: flex; gap: 1.5rem; margin: 1.5rem 0; }
    .nav a { padding: 0.5rem 1rem; background: #f0f0f0; border-radius: 6px; font-weight: 500; }
    .nav a:hover { background: #e0e0e0; text-decoration: none; }
  </style>
</head>
<body>
  <h1>embed-code-ts</h1>
  <p class="subtitle">nomic-embed-code int8 ONNX for Node.js — v${PKG_JSON.version}</p>

  <div class="nav">
    <a href="./api/index.html">API Documentation</a>
    <a href="./coverage/index.html">Coverage Report</a>
    <a href="./benchmark/benchmark-report.json">Benchmark Data (JSON)</a>
    <a href="https://github.com/AgentiX-E/embed-code-ts">GitHub Repository</a>
  </div>

  <h2>Packages</h2>
  <table>
    <tr><th>Package</th><th>Description</th><th>API Docs</th></tr>
    <tr>
      <td><code>@agentix-e/embed-code-core</code></td>
      <td>Core inference engine for code embeddings</td>
      <td><a href="./api/modules.html">TypeDoc</a></td>
    </tr>
    <tr>
      <td><code>@agentix-e/embed-code-cli</code></td>
      <td>Command-line interface</td>
      <td><a href="./api/modules/embed_code_cli_src_cli.html">CLI API</a></td>
    </tr>
  </table>

  <h2>Benchmarks</h2>
  ${benchmarkData ? `<p>Model: <strong>${benchmarkData.model}</strong> | Dim: ${benchmarkData.embeddingDim} | Node.js ${benchmarkData.system?.nodeVersion || '?'} | ${benchmarkData.system?.platform || '?'}/${benchmarkData.system?.arch || '?'}</p>` : '<p>No benchmark data available.</p>'}
  <table>
    <tr><th>Config</th><th>Batch</th><th>Avg Latency</th><th>Throughput</th></tr>
    ${benchmarkTable()}
  </table>
  ${
    benchmarkData?.memory
      ? `
  <h2>Memory</h2>
  <table>
    <tr><th>Heap Used</th><th>Heap Total</th><th>RSS</th></tr>
    <tr>
      <td>${benchmarkData.memory.heapUsedMB} MB</td>
      <td>${benchmarkData.memory.heapTotalMB} MB</td>
      <td>${benchmarkData.memory.rssMB} MB</td>
    </tr>
  </table>`
      : ''
  }

  <h2>Coverage</h2>
  <p>${coveragePct !== null ? `<span class="badge ${coveragePct >= 95 ? 'badge-green' : 'badge-yellow'}">${coveragePct}%</span>` : 'No coverage data available.'}</p>

  <hr style="margin-top: 2rem;">
  <p style="color: #999; font-size: 0.85rem;">Generated by embed-code-ts CI — <a href="https://github.com/AgentiX-E/embed-code-ts">GitHub</a></p>
</body>
</html>
`;

fs.writeFileSync(path.join(DOCS_DIR, 'index.html'), html);
console.log('Pages prepared: docs/index.html');
