/**
 * @generated — DO NOT EDIT
 * Auto-generated weights index
 * Generated at build time
 */

// These are generated by the incbin build script.
// Run `npm run build:weights` to populate.

export {};
