// Placeholder — generated by incbin at build time
export const MODEL_MANIFEST = {
  modelId: 'nomic-embed-code-v1',
  provider: 'remote',
  remote: { baseUrl: '', chunkCount: 0, sha256: '', totalSize: 0 },
  runtime: { embeddingDim: 3584, maxTokens: 32768, poolingStrategy: 'last_token', normalize: true },
  version: 1,
} as const;
