/**
 * Model Provider Factory
 *
 * Creates the appropriate IModelProvider based on the model descriptor's provider type.
 * This is the single entry point for model loading — whether weights are fully embedded,
 * chunk-embedded, or remotely downloaded.
 */

import type { IModelProvider, ModelDescriptor, EmbedCodeOptions } from './types';
import { EmbeddedModelProvider } from './providers/embedded-provider';
import { ChunkedModelProvider } from './providers/chunked-provider';
import { RemoteModelProvider } from './providers/remote-provider';

/**
 * Create a model provider based on the model descriptor and user options.
 */
export async function createModelProvider(
  descriptor: ModelDescriptor,
  options: EmbedCodeOptions = {},
): Promise<IModelProvider> {
  // User can override the provider type
  const providerType = options.provider ?? descriptor.provider;

  // Load tokenizer data — always embedded (small enough)
  const tokenizerData = await loadTokenizerData(descriptor);

  switch (providerType) {
    case 'embedded': {
      // Layer 1: Fully embedded — weights are compiled into the bundle
      const weights = await loadEmbeddedWeights(descriptor);
      return new EmbeddedModelProvider(descriptor, weights, tokenizerData);
    }

    case 'chunked': {
      // Layer 2: Chunked embedded — weights split across lazy-loaded modules
      const { manifest, loadChunk } = await loadChunkedWeights(descriptor);
      return new ChunkedModelProvider(
        descriptor,
        manifest,
        loadChunk,
        tokenizerData,
        options.onProgress,
      );
    }

    case 'remote': {
      // Layer 3: Remote download — only manifest is embedded
      return new RemoteModelProvider(
        descriptor,
        tokenizerData,
        options.onProgress,
        options.cacheDir,
      );
    }

    default:
      throw new Error(`Unknown provider type: ${providerType}`);
  }
}

// ─── Data Loaders ──────────────────────────────────────────

async function loadTokenizerData(
  descriptor: ModelDescriptor,
): Promise<{ base64: string; sha256: string }> {
  // Dynamic import of the embedded tokenizer data
  // In production, this is generated by the incbin build script
  try {
    const mod = await import('../weights/tokenizer.inc');
    return {
      base64: mod.TOKENIZER_BASE64,
      sha256: mod.TOKENIZER_SHA256,
    };
  } catch {
    // Fallback: tokenizer not embedded, will be loaded from HF
    return { base64: '', sha256: '' };
  }
}

async function loadEmbeddedWeights(
  descriptor: ModelDescriptor,
): Promise<{ WEIGHT_BASE64: string; WEIGHT_SHA256: string; WEIGHT_SIZE: number }> {
  try {
    const mod = await import('../weights/model.inc');
    return {
      WEIGHT_BASE64: mod.MODEL_BASE64,
      WEIGHT_SHA256: mod.MODEL_SHA256,
      WEIGHT_SIZE: mod.MODEL_SIZE,
    };
  } catch {
    throw new Error(
      `Embedded weights not found for model "${descriptor.id}". ` +
        'Run "npm run build:weights" to generate them.',
    );
  }
}

async function loadChunkedWeights(
  descriptor: ModelDescriptor,
): Promise<{
  manifest: ChunkManifest;
  loadChunk: (index: number) => Promise<any>;
}> {
  try {
    const manifestMod = await import('../weights/chunk.manifest');
    const manifest = manifestMod.CHUNK_MANIFEST;

    const loadChunk = async (index: number) => {
      // Dynamic import of individual chunk modules
      // e.g., import('../weights/model.int8.chunk_0000.inc')
      const chunkPath = `../weights/model.int8.chunk_${String(index).padStart(4, '0')}.inc`;
      return import(chunkPath);
    };

    return { manifest, loadChunk };
  } catch {
    throw new Error(
      `Chunked weights not found for model "${descriptor.id}". ` +
        'Run "npm run build:weights" to generate them.',
    );
  }
}

// Re-export for use elsewhere
interface ChunkManifest {
  totalSize: number;
  sha256: string;
  chunkSize: number;
  chunkCount: number;
  chunks: Array<{
    index: number;
    offset: number;
    size: number;
    sha256: string;
  }>;
}
